import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { projectName, datasets, visualizations, insights, includeCharts, includeInsights, includeSummary } = await req.json();
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    const totalRows = datasets?.reduce((s: number, d: any) => s + (d.row_count || 0), 0) || 0;

    let reportContent = `# ${projectName || "Report"}\n\n`;
    reportContent += `**Generated:** ${new Date().toISOString().split("T")[0]}\n\n---\n\n`;

    if (includeSummary) {
      reportContent += `## Executive Summary\n\n`;
      reportContent += `| Metric | Value |\n|--------|-------|\n`;
      reportContent += `| Datasets | ${datasets?.length || 0} |\n`;
      reportContent += `| Visualizations | ${visualizations?.length || 0} |\n`;
      reportContent += `| Total Data Points | ${totalRows.toLocaleString()} |\n\n`;
    }

    // Use AI to generate a comprehensive summary
    const aiPrompt = `Generate a professional executive summary for a data analytics report with the following context:
- Project: ${projectName}
- Datasets: ${datasets?.map((d: any) => `${d.name} (${d.row_count} rows, columns: ${JSON.stringify(d.columns)})`).join("; ")}
- Visualizations: ${visualizations?.length || 0} charts
- Key insights: ${JSON.stringify(insights?.slice(0, 10))}

Write 3-4 paragraphs covering key findings, data quality, and recommendations. Be specific with numbers.`;

    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: "You are a professional data analyst writing executive reports. Be concise and data-driven." },
          { role: "user", content: aiPrompt },
        ],
      }),
    });

    if (aiResponse.ok) {
      const aiResult = await aiResponse.json();
      const aiContent = aiResult.choices?.[0]?.message?.content || "";
      if (aiContent) {
        reportContent += `## AI Analysis\n\n${aiContent}\n\n---\n\n`;
      }
    }

    if (includeInsights && insights?.length > 0) {
      reportContent += `## Key Insights\n\n`;
      insights.forEach((insight: any) => {
        const emoji = insight.severity === "critical" ? "🔴" : insight.severity === "warning" ? "🟡" : "🟢";
        reportContent += `${emoji} **${insight.title}:** ${insight.text}${insight.metric ? ` *(${insight.metric})*` : ""}\n\n`;
      });
      reportContent += `---\n\n`;
    }

    if (includeCharts && visualizations?.length > 0) {
      reportContent += `## Visualizations\n\n`;
      visualizations.forEach((v: any) => {
        reportContent += `- **${v.name}** — Type: ${v.chart_type}${v.ai_explanation ? ` — ${v.ai_explanation}` : ""}\n`;
      });
      reportContent += `\n---\n\n`;
    }

    if (datasets?.length > 0) {
      reportContent += `## Data Sources\n\n`;
      datasets.forEach((ds: any) => {
        reportContent += `### ${ds.name}\n`;
        reportContent += `- **Type:** ${ds.file_type?.toUpperCase()}\n`;
        reportContent += `- **Rows:** ${(ds.row_count || 0).toLocaleString()}\n`;
        reportContent += `- **Columns:** ${ds.column_count || 0}\n`;
        reportContent += `- **Columns:** ${(ds.columns as string[])?.join(", ") || "N/A"}\n\n`;
      });
    }

    reportContent += `\n---\n*Report generated by AutoInsight AI on ${new Date().toLocaleString()}*\n`;

    return new Response(JSON.stringify({ report: reportContent }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("generate-report error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
