// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

const oauthBrokerUrl = import.meta.env.VITE_LOVABLE_OAUTH_BROKER_URL ?? "https://oauth.lovable.app/~oauth/initiate";
const lovableAuth = createLovableAuth({
  oauthBrokerUrl,
  supportedOAuthOrigins: [
    "https://oauth.lovable.app",
    "https://lovable.dev",
    typeof window !== "undefined" ? window.location.origin : "",
  ].filter(Boolean),
});

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
